project_id = "ytkmoujvriqetljjfito"

[functions.musicbrainz]
verify_jwt = false

[functions.real-debrid]
verify_jwt = false

[functions.home-content]
verify_jwt = false

[functions.squidwtf]
verify_jwt = false

[functions.check-new-releases]
verify_jwt = false
schedule = "0 8 * * *"

[functions.send-broadcast-notification]
verify_jwt = false
